name: JARAM
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_login:
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  intl: ^0.16.1
  http:
  provider: ^3.1.0
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  # flutter_test from sdk depends on quiver 2.0.5
  quiver: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  
flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/Jaram.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
      - family: OpenSans
        fonts:
          - asset: assets/fonts/OpenSans-Light.ttf
            weight: 300
          - asset: assets/fonts/OpenSans-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/OpenSans-Regular.ttf
          - asset: assets/fonts/OpenSans-Italic.ttf
            style: italic
          - asset: assets/fonts/OpenSans-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/OpenSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/OpenSans-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/OpenSans-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
            weight: 800
            style: italic
      - family: SourceSansPro
        fonts:
          - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
            weight: 200
          - asset: assets/fonts/SourceSansPro-Light.ttf
            weight: 300
          - asset: assets/fonts/SourceSansPro-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/SourceSansPro-Regular.ttf
          - asset: assets/fonts/SourceSansPro-Italic.ttf
            style: italic
          - asset: assets/fonts/SourceSansPro-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/SourceSansPro-Bold.ttf
            weight: 700
          - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
            weight: 700
            style: italic
      - family: NotoSans
        fonts:
          - asset: assets/fonts/NotoSans-Regular.ttf
          - asset: assets/fonts/NotoSans-Italic.ttf
            style: italic
          - asset: assets/fonts/NotoSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/NotoSans-BoldItalic.ttf
            weight: 700
            style: italic
      - family: Quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Light.ttf
            weight: 300
          - asset: assets/fonts/Quicksand-Regular.ttf
          - asset: assets/fonts/Quicksand-Medium.ttf
            weight: 500
          - asset: assets/fonts/Quicksand-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Quicksand-Bold.ttf
            weight: 700
